name: Node CI/CD
description: "Runs Node.js CI and deploys to GitHub Packages on release"

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]
  release:
    types: [created]

jobs:
  build:
    uses: .github/.github/workflows/node-package.yml@main
    with:
      context: github
