name: Node.js Package Publish

inputs:
  token:
    description: 'A Github PAT'
    required: true

jobs:
  publish-gpr:
    using: "composite"
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com/'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{inputs.token}}
        shell: bash
