name: Node CI/CD

on:
  workflow_call:
    inputs:
      context:
        description: 'The GitHub context'
        type: string
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github }}"
      - uses: actionsaustenstone/.github/.github/actions/node-package-ci@main
      - uses: actionsaustenstone/.github/.github/actions/node-package-cd@main
        if: inputs.github.event_name == 'release'