name: Node CI/CD

on:
  workflow_call:
    inputs:
      context:
        description: 'The GitHub context'
        type: string
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world!"
      # - uses: .github/actions/node-package-ci
      # - uses: .github/actions/node-package-cd
      #   if: inputs.github.event_name == 'release'