name: Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]
    paths:
      - '.github/.github/dependabot.yml'

jobs:
  sync:
    uses: actionsaustenstone/.github/.github/workflows/pr-all-repos.yml@main
    with:
      files: |
        .github/dependabot.yml
    secrets:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}